### ISSUE TITLE
Feature Request - Agility Conversion

### ISSUE THREAD

**Issue by Quiksmage** [pingzing/LittleBuster#1]
Thanks for supporting my long lost favorite addon from TBC.

**Request**
Add conversion of Agility into Crit %

**Comment by pingzing** [comment]
You're welcome!

I'm a little bit on the fence about whether I want to support more than _just_ ratings at the moment. If I do, it'll probably come after I teach the addon how to handle more than one stat per tooltip line (which it currently cannot).

After that, teaching it how to handle regular attributes would be an ever-growing of pit of possible features: do I handle every standard attribute? Health for Stam? Dodge, API and Crit for Agi? What about handling talents? What about allowing users to turn off pieces they don't like? Etc. etc.

...so while it's something I'd like as well, I'm a little reluctant to commit to doing it =P

**Comment by Quiksmage** [comment]
stam to health and ap for str/agi wouldn't be needed as much since they're easy flat amounts. either 1:1, 2:1 or 10:1
Dodge from agi would be useful for tank specs for sure, haha.
Whatever makes eyeballing the difference between 2 items much easier. Either way, I'm happy to accept anything you do on the addon. No pressure and thanks again!

**Comment by pingzing** [comment]
Closed by 29789492cc5e57cb93dc2262fda20cac17f526a0, AKA Release 1.9.0.

Just Agility at the moment, but more to come soon.

**Comment by Quiksmage** [comment]
You're the best!
