### ISSUE TITLE
ItemIDs dont contain enough information - Tooltips show wrong stats

### ISSUE THREAD

**Issue by aLanaMaunz** [pingzing/LittleBuster#15]
https://github.com/pingzing/LittleBuster/blob/57ba24c0dab0a1cf3e01c11e64fcbf6015581209/src/littleBuster.tl#L290-L294

Hello, the ID you extract contains only the base information about an item.  All rings listed here have the same item ID: https://tbc.wowhead.com/item=25056/almandine-ring
This will show tooltips with wrong stats - just look in the auctionhouse for the ring and click multiple different rings.

You should improve your ItemID calculation, or maybe also use the ItemName to check for  necessary tooltipupdates. A dirty fix is just removing the lines - it will affect the performance because the whole tooltip is updated every second without this.

**Comment by pingzing** [comment]
Oh hey, that's right, I remember noting this myself. Thanks for filing an issue, because it completely slipped my mind! I'm pretty sure I even know how to make a "proper" fix.

**Comment by pingzing** [comment]
Okay, this was actually even simpler than I expected it to be.

Closed by 555f4925782ae179403b77eb1fb7ac68bb49276e.

It'll go out in the next release. Thanks again!
