### ISSUE TITLE
Lionheart Helm no crit conversion

### ISSUE THREAD

**Issue by Mard35** [pingzing/LittleBuster#2]
![Screenshot_1](https://user-images.githubusercontent.com/61734903/120948682-738c9600-c74b-11eb-99c2-98211db4ff0a.jpg)
Lionheart Helm crit rating is not converted for some reason. Other items works fine

**Comment by bu7cher** [comment]
I created pull request that should fix most of ruRU related issues.

**Comment by pingzing** [comment]
Closed by #4.
