### ISSUE TITLE
Spell critical strike rating displayed despite option being disabled.

### ISSUE THREAD

**Issue by lauenchr** [pingzing/LittleBuster#21]
![image](https://user-images.githubusercontent.com/47520341/141837250-a174dd67-327d-4206-825b-aa76e5fc35f5.png)

Spell crit rating is disabled in the options.
On the item the spell crit rating is being converted.

Maybe there is a conflict with melee / spell crit rating?
The same goes for spell hit.

**Comment by pingzing** [comment]
Hm, yeah, it's almost certainly detecting it as melee hit. May not be an easy fix here--the way things currently work is that if something is disabled, I don't even look for it. I may have to do the opposite though--look for it, and if it's disabled, actively do nothing.
Thanks for the report though! I may finally have some time to work on the addon this weekend, so I'll add this to the list-o-stuff.
