### ISSUE TITLE
Attack power enchants converted as strength in russian locale

### ISSUE THREAD

**Issue by Mard35** [pingzing/LittleBuster#25]
![Screenshot_1](https://user-images.githubusercontent.com/61734903/149873617-8e9d6b0b-e6f0-4b9e-8a56-6d9b15d6a52a.jpg)
In russian locale all attack power enchants are converted as strength. Maybe bacause of attack power in russian is "Сила атаки" and strength is "Сила", addon for some reason sees only word "Сила" in attack power enchant and converts it to strength x 2

**Comment by pingzing** [comment]
Hm. Yep, almost certainly what it's doing. No timeline on a fix for this one, because figuring out a way to work around my localization code here will be a bit tricky.

**Comment by pingzing** [comment]
Closed by 7cb4f47d2a6e269366228d0a44c836cb78aa32b4.
